version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          name: Run Cypress tests
          start: npm start
          wait-on: 'http://localhost:8080'
          no-workspace: true
          record: true
          tags: 'smoke,qa_env'